//go:build !ignore_autogenerated

// Copyright (c) 2026 Volodymyr Ajentik
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotation) DeepCopyInto(out *JWKSRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotation.
func (in *JWKSRotation) DeepCopy() *JWKSRotation {
	if in == nil {
		return nil
	}
	out := new(JWKSRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWKSRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationList) DeepCopyInto(out *JWKSRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JWKSRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationList.
func (in *JWKSRotationList) DeepCopy() *JWKSRotationList {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWKSRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationPolicy) DeepCopyInto(out *JWKSRotationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationPolicy.
func (in *JWKSRotationPolicy) DeepCopy() *JWKSRotationPolicy {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWKSRotationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationPolicyList) DeepCopyInto(out *JWKSRotationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JWKSRotationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationPolicyList.
func (in *JWKSRotationPolicyList) DeepCopy() *JWKSRotationPolicyList {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JWKSRotationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationPolicySpec) DeepCopyInto(out *JWKSRotationPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.RotationInterval = in.RotationInterval
	out.RetentionPeriod = in.RetentionPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationPolicySpec.
func (in *JWKSRotationPolicySpec) DeepCopy() *JWKSRotationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationPolicyStatus) DeepCopyInto(out *JWKSRotationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationPolicyStatus.
func (in *JWKSRotationPolicyStatus) DeepCopy() *JWKSRotationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationSpec) DeepCopyInto(out *JWKSRotationSpec) {
	*out = *in
	out.RotationInterval = in.RotationInterval
	out.RetentionPeriod = in.RetentionPeriod
	out.TargetSecret = in.TargetSecret
	if in.TargetDeployments != nil {
		in, out := &in.TargetDeployments, &out.TargetDeployments
		*out = make([]TargetDeploymentRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationSpec.
func (in *JWKSRotationSpec) DeepCopy() *JWKSRotationSpec {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKSRotationStatus) DeepCopyInto(out *JWKSRotationStatus) {
	*out = *in
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
	if in.NextRotation != nil {
		in, out := &in.NextRotation, &out.NextRotation
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKSRotationStatus.
func (in *JWKSRotationStatus) DeepCopy() *JWKSRotationStatus {
	if in == nil {
		return nil
	}
	out := new(JWKSRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDeploymentRef) DeepCopyInto(out *TargetDeploymentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDeploymentRef.
func (in *TargetDeploymentRef) DeepCopy() *TargetDeploymentRef {
	if in == nil {
		return nil
	}
	out := new(TargetDeploymentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecretRef) DeepCopyInto(out *TargetSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSecretRef.
func (in *TargetSecretRef) DeepCopy() *TargetSecretRef {
	if in == nil {
		return nil
	}
	out := new(TargetSecretRef)
	in.DeepCopyInto(out)
	return out
}
