name: Helm Chart Validation

on:
  pull_request:
    paths:
      - 'dist/chart/**'

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validate:
    name: Lint and Template
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        # actions/checkout@v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install Helm
        # azure/setup-helm@v4
        uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a

      - name: Lint chart
        run: helm lint dist/chart/

      - name: Render templates
        run: helm template jwks-rotater dist/chart/
